//------------------------------------------------------------------------------
// <auto-generated>
//     This sipc was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the sipc is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMM
{


    public partial class ServiceTest
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to sipc-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
