CREATE TABLE [dbo].[DATAMIGRATION_BMM_TEST_BMM]
(
[Invoice Number] [int] NULL,
[Invoice Date] [datetime] NULL,
[Client Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client Last Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client Address] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client Zip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client WorkPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client Date of Birth] [datetime] NULL,
[SSN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Of Accident] [datetime] NULL,
[Attorney No] [int] NULL,
[Physician No] [int] NULL,
[Provider No] [int] NULL,
[Invoice Closed] [bit] NULL,
[Notes] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice Closed Date] [datetime] NULL,
[TotalCost] [float] NULL,
[MaturityDate] [datetime] NULL,
[DepositReceived] [float] NULL,
[DatePaid] [datetime] NULL,
[DueDate] [datetime] NULL,
[ServiceFeeWaived] [float] NULL,
[AmountPaid] [float] NULL,
[BalanceDue] [float] NULL,
[DateServiceFeeBegins] [datetime] NULL,
[LossesAmount] [float] NULL,
[Cumulative] [float] NULL,
[CostOfGoodsSold] [float] NULL,
[EndingBalance] [float] NULL,
[Revenue] [float] NULL,
[AmortizationDate] [datetime] NULL,
[Months] [int] NULL,
[TotalPayments] [float] NULL,
[TotalPPO] [float] NULL,
[TotalPrincipal] [float] NULL,
[CompleteFile] [bit] NULL,
[company] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalInterestPaid] [float] NULL,
[GrossCumulative] [float] NULL,
[transferred] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
